### ISSUE TITLE
Disabling Personally Identifiable Information (PII)

### ISSUE THREAD

**Issue by saarikivit** [amplitude/Amplitude-Flutter-Deprecated#74]
Hello!

Is there any way for me to disable tracking, for example, the IP address and the UDID?

I'm working on a children's app and according to Apple, they do not allow developers to collect PII on 3rd party analytics providers.

If it is possible, thanks for your time and assistance! 🙏 

If however, it is not possible I'd like to offer my helping hand in contributing to the effort if needed. ✋ 

I can see the Android and iOS SDKs having the possibility:

https://help.amplitude.com/hc/en-us/articles/115002935588#disable-automatic-tracking-of-user-properties

https://help.amplitude.com/hc/en-us/articles/115002278527-iOS-SDK-Installation#disable-automatic-tracking-of-user-properties

What do you think?

**Comment by haoliu-amp** [comment]
Hello @saarikivit , 

It's correct that our native SDKs support those operations. In order not to implement the same logic again and again, we decide we'll create a new Flutter SDK which bridge the call to our native SDKs. And I just started doing that. I will create the basic modules first and check it into another repo. I should get it in sometime this week.

And I appreciate your offer for helping this. So basically you can just follow the pattern to add the bridging logic if you need any APIs from native SDKs.

**Comment by saarikivit** [comment]
I noticed the flutter library was bumped to 2.0.0. That is giving me exactly what I want 😁
Bless 🙏

**Comment by haoliu-amp** [comment]
@saarikivit Very pleased to hear this! Hope new SDK can help you better!
